# This Makefile was generated by the ThirdCake
# https://github.com/grwlf/cake3

GUARD = .GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)
URFLAGS = 
.PHONY: all
all : resetdb FooCMS.exe
.PHONY: resetdb
resetdb : ./filldb.sh FooCMS.sql FooCMS.db FooCMS.db style.css file.markdown
	-rm -rf FooCMS.db
	sqlite3 FooCMS.db < FooCMS.sql
	./filldb.sh
.INTERMEDIATE:stamp1
stamp1 : FooCMS.urp src/Auth.ur src/Lite.ur tst/ref.ur tst/refFun.ur tst/link.ur $(call GUARD,URFLAGS)
	urweb $(URFLAGS) -dbms sqlite FooCMS
FooCMS.sql FooCMS.exe : stamp1
FooCMS.db : 
	touch FooCMS.db
Makefile : Cakegen
	./Cakegen > Makefile
Cakegen : ./Cakefile.hs
	cake3
.PHONY: tc
tc : 
	urweb  FooCMS
$(call GUARD,URFLAGS) :
	rm -f .GUARD_URFLAGS_*
	touch $@

