# This Makefile was generated by the ThirdCake
# https://github.com/grwlf/cake3

GUARD = .GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)
URFLAGS = 
.PHONY: all
all : FooCMS.exe FooCMS.db Makefile
FooCMS.db : FooCMS.sql FooCMS.exe Makefile
	-rm -rf FooCMS.db
	sqlite3 FooCMS.db < FooCMS.sql
.INTERMEDIATE:stamp1
stamp1 : lib/static/lib.urp lib/jqmenu/JQM.ur lib/jqmenu/JQM.urs lib/jqmenu/JQM_wrapper.urs lib/jqmenu/lib.urp lib/uwprocess/process.urs lib/uwprocess/lib.urp src/Lite.ur src/Lite.urs ./FooCMS.urp Makefile $(call GUARD,URFLAGS)
	urweb $(URFLAGS) -dbms sqlite FooCMS
	touch FooCMS.sql FooCMS.exe
FooCMS.sql FooCMS.exe : stamp1
lib/static/lib.urp : lib/jqmenu/JQM.js content/article.html src/Style.css Makefile
	mkdir -pv lib/static
	./mkres.sh lib/static src/Style.css content/article.html lib/jqmenu/JQM.js
content/article.html : content/article.markdown Makefile
	pandoc -f markdown -t html content/article.markdown > content/article.html
Makefile : ./Cakefile.hs
	cake3
$(call GUARD,URFLAGS) :
	rm -f .GUARD_URFLAGS_*
	touch $@

