# This Makefile was generated by the ThirdCake
# https://github.com/grwlf/cake3

GUARD = .GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)
URFLAGS = 
.PHONY: all
all : FooCMS.exe FooCMS.db Makefile
FooCMS.db : FooCMS.sql FooCMS.exe Makefile
	-rm -rf FooCMS.db
	sqlite3 FooCMS.db < FooCMS.sql
.INTERMEDIATE:stamp1
stamp1 : src/static/JQM_js.urp src/static/Article_html.urp src/static/Style_css.urp src/uwprocess/process.urs src/uwprocess/lib.urp src/Lite.ur src/Lite.urs ./FooCMS.urp Makefile $(call GUARD,URFLAGS)
	urweb $(URFLAGS) -dbms sqlite FooCMS
	touch FooCMS.sql FooCMS.exe
FooCMS.sql FooCMS.exe : stamp1
src/static/JQM_js.urp : src/JQM.js Makefile
	mkdir -pv src/static
	urembed -o src/static src/JQM.js
src/static/Article_html.urp : content/article.html Makefile
	mkdir -pv src/static
	urembed -o src/static content/article.html
src/static/Style_css.urp : src/Style.css Makefile
	mkdir -pv src/static
	urembed -o src/static src/Style.css
Makefile : ./Cakefile.hs
	cake3
$(call GUARD,URFLAGS) :
	rm -f .GUARD_URFLAGS_*
	touch $@

